### ISSUE TITLE
Script fails to run in Violentmonkey

### ISSUE THREAD

**Issue by arogl** [buzz/imdb-link-em-all#35]
As per [Something is wrong with the latest update 2.0.2 the script stopped working - GreasyFork](https://greasyfork.org/en/scripts/17154-imdb-link-em-all/discussions/61164) I am experirencing the same error:

Browser: Firefox 80.0
OS: Win10 2004 latest patch
Userscript extension: ViolentMonkey 2.12.7
Userscript version: 2.0.4
Open the developer console of your browser. Copy and paste any error messages you spot there.

```
Uncaught TypeError: 'cancelAnimationFrame' called on an object that does not implement interface Window.
    u moz-extension://beb47c15-98e0-4f42-972b-d192b8bf4042/IMDb： Link ＇em all!.user.js#176:136
line 1 > injectedScript:136:1317
    u moz-extension://beb47c15-98e0-4f42-972b-d192b8bf4042/IMDb： Link ＇em all!.user.js#176:136
```

**Comment by arogl** [comment]
Works in
TamperMonkey Beta v4.11.6119
ViolentMonkey v2.12.8 Release Candidate 15

**Comment by buzz** [comment]
The extension also works in TamperMonkey 4.10 and others. I suggest to use another Userscript extension or wait for the next ViolentMonkey release. Closing this.
